### ISSUE TITLE
Improve build tools

### ISSUE THREAD

**Issue by clitetailor** [clitetailor/cursornext#3]
The main target of this issue is to improve build tools for this project. I would like to use Gulp and Rollup as project build tools. The basic output should supports `cjs` and `umd` format. Every `cjs` output files should be placed at the root folder so that the following code should works:

```js
const { t } = require('cursornext/test')
```

Hence, every output `.js` files should be added to `.gitignore` except build (and other tools) configuration files.

Hope that this is not too much for one issue, contributions are welcome!

**Comment by nutboltu** [comment]
@clitetailor any specific reason for not willing to use `webpack`?

**Comment by clitetailor** [comment]
@nutboltu Yeap, `webpack` is a bundling tool means that it works better for web app where everything is bundled into one single file. I prefer `gulp` because:
- For `cjs` output i want to keep output files seperated, which works better on NodeJS env.
- `gulp` is a task runner so i can build, run and test programmatically if i want.
- `gulp` v4 API is so simple and expressive.

I haven't update infomation about webpack for a while so i don't know whether any thing new since v4. IMO, gulp is still much more reasonable about than using webpack complex centralized configuration style.

**Comment by clitetailor** [comment]
One thing added, if you know `typescript` well, you don't even need any other build tool for `typescript`, just put some `tsconfig.json` files into `src` folder and run `tsc -p ...` then everything will be completed.

I want to use `gulp` and `rollup` here is because want to run it though `babel-typescript` which i can transpile or add more features if needed. For `rollup`, it may yell some warnings if the you have cyclic dependencies, etc ... . I'd love people to works with `rollup` because they tends to know better about output formats either.

**Comment by nutboltu** [comment]
Thanks for the detail explanation. I probably have a look into it. I will let you know if I am able to open a PR for this issue
